config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   resources :apartments

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :owner
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :apartments
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  def index
    @apartments = Apartment.all
  end

  def show
    @apartment = Apartment.find(params[:id])
    @owner = @apartment.owner
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end


end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apartments/index.html.erb
<h1>Our Apartments</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>City</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @apartments.each do |apartment| %>
  <tr>
    <td><%= link_to apartment.title, apartment_path(apartment)%></td>
    <td><%= apartment.city %></td>
    <td><%= apartment.price %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/apartments/show.html.erb
<h1><%= @apartment.title %></h1>

<h2>Apartment</h2>

<p>description : <%= @apartment.description %></p>
<p>adress : <%= @apartment.adress %></p>
<p>zipcode : <%= @apartment.zipcode %></p>
<p>city : <%= @apartment.city %></p>
<p>country : <%= @apartment.country %></p>
<p>price / night : <%= @apartment.price %></p>

<h2>Owner</h2>

<p>First name : <%= @owner.first_name %></p>
<p>Last name : <%= @owner.last_name %></p>
<p>Email : <%= @owner.email %></p>

<%= link_to 'All Apartments' , apartments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirbnbBadass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to our BadAss Airbnb community !</h1>

<%= link_to 'All Apartments' , apartments_path %>